name: primekg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - goatools
  - beautifulsoup4
  - psycopg2
  - sqlalchemy
  - tqdm
  - python-igraph
  - scipy
  - scikit-learn
  - cudatoolkit
  - pip:
    - torch
    - transformers